//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_Brand", "tbl_Brand", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.tbl_Brand), "tbl_Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.tbl_Product), true)]
[assembly: EdmRelationshipAttribute("db_OnlineShopModel", "FK_tbl_AddSeller_tbl_Gender", "tbl_Gender", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.tbl_Gender), "tbl_Seller", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.tbl_Seller), true)]
[assembly: EdmRelationshipAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_ProductType", "tbl_ProductType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.tbl_ProductType), "tbl_Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.tbl_Product), true)]
[assembly: EdmRelationshipAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_Seller", "tbl_Seller", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.tbl_Seller), "tbl_Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.tbl_Product), true)]

#endregion

namespace DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db_OnlineShopEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db_OnlineShopEntities object using the connection string found in the 'db_OnlineShopEntities' section of the application configuration file.
        /// </summary>
        public db_OnlineShopEntities() : base("name=db_OnlineShopEntities", "db_OnlineShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_OnlineShopEntities object.
        /// </summary>
        public db_OnlineShopEntities(string connectionString) : base(connectionString, "db_OnlineShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db_OnlineShopEntities object.
        /// </summary>
        public db_OnlineShopEntities(EntityConnection connection) : base(connection, "db_OnlineShopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Brand> tbl_Brand
        {
            get
            {
                if ((_tbl_Brand == null))
                {
                    _tbl_Brand = base.CreateObjectSet<tbl_Brand>("tbl_Brand");
                }
                return _tbl_Brand;
            }
        }
        private ObjectSet<tbl_Brand> _tbl_Brand;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Customer> tbl_Customer
        {
            get
            {
                if ((_tbl_Customer == null))
                {
                    _tbl_Customer = base.CreateObjectSet<tbl_Customer>("tbl_Customer");
                }
                return _tbl_Customer;
            }
        }
        private ObjectSet<tbl_Customer> _tbl_Customer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Gender> tbl_Gender
        {
            get
            {
                if ((_tbl_Gender == null))
                {
                    _tbl_Gender = base.CreateObjectSet<tbl_Gender>("tbl_Gender");
                }
                return _tbl_Gender;
            }
        }
        private ObjectSet<tbl_Gender> _tbl_Gender;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Product> tbl_Product
        {
            get
            {
                if ((_tbl_Product == null))
                {
                    _tbl_Product = base.CreateObjectSet<tbl_Product>("tbl_Product");
                }
                return _tbl_Product;
            }
        }
        private ObjectSet<tbl_Product> _tbl_Product;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ProductType> tbl_ProductType
        {
            get
            {
                if ((_tbl_ProductType == null))
                {
                    _tbl_ProductType = base.CreateObjectSet<tbl_ProductType>("tbl_ProductType");
                }
                return _tbl_ProductType;
            }
        }
        private ObjectSet<tbl_ProductType> _tbl_ProductType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Seller> tbl_Seller
        {
            get
            {
                if ((_tbl_Seller == null))
                {
                    _tbl_Seller = base.CreateObjectSet<tbl_Seller>("tbl_Seller");
                }
                return _tbl_Seller;
            }
        }
        private ObjectSet<tbl_Seller> _tbl_Seller;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Brand EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Brand(tbl_Brand tbl_Brand)
        {
            base.AddObject("tbl_Brand", tbl_Brand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Customer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Customer(tbl_Customer tbl_Customer)
        {
            base.AddObject("tbl_Customer", tbl_Customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Gender EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Gender(tbl_Gender tbl_Gender)
        {
            base.AddObject("tbl_Gender", tbl_Gender);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Product(tbl_Product tbl_Product)
        {
            base.AddObject("tbl_Product", tbl_Product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ProductType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ProductType(tbl_ProductType tbl_ProductType)
        {
            base.AddObject("tbl_ProductType", tbl_ProductType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Seller EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Seller(tbl_Seller tbl_Seller)
        {
            base.AddObject("tbl_Seller", tbl_Seller);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_OnlineShopModel", Name="tbl_Brand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Brand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Brand object.
        /// </summary>
        /// <param name="brand_ID">Initial value of the Brand_ID property.</param>
        /// <param name="brand">Initial value of the Brand property.</param>
        public static tbl_Brand Createtbl_Brand(global::System.Int32 brand_ID, global::System.String brand)
        {
            tbl_Brand tbl_Brand = new tbl_Brand();
            tbl_Brand.Brand_ID = brand_ID;
            tbl_Brand.Brand = brand;
            return tbl_Brand;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Brand_ID
        {
            get
            {
                return _Brand_ID;
            }
            set
            {
                if (_Brand_ID != value)
                {
                    OnBrand_IDChanging(value);
                    ReportPropertyChanging("Brand_ID");
                    _Brand_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Brand_ID");
                    OnBrand_IDChanged();
                }
            }
        }
        private global::System.Int32 _Brand_ID;
        partial void OnBrand_IDChanging(global::System.Int32 value);
        partial void OnBrand_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_Brand", "tbl_Product")]
        public EntityCollection<tbl_Product> tbl_Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Product>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Brand", "tbl_Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Product>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Brand", "tbl_Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_OnlineShopModel", Name="tbl_Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Customer object.
        /// </summary>
        /// <param name="customer_ID">Initial value of the Customer_ID property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="company_Name">Initial value of the Company_Name property.</param>
        /// <param name="contact">Initial value of the Contact property.</param>
        /// <param name="street_Address">Initial value of the Street_Address property.</param>
        /// <param name="postal_Code">Initial value of the Postal_Code property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        public static tbl_Customer Createtbl_Customer(global::System.Int32 customer_ID, global::System.String email, global::System.String password, global::System.String company_Name, global::System.String contact, global::System.String street_Address, global::System.String postal_Code, global::System.String city, global::System.String country)
        {
            tbl_Customer tbl_Customer = new tbl_Customer();
            tbl_Customer.Customer_ID = customer_ID;
            tbl_Customer.Email = email;
            tbl_Customer.Password = password;
            tbl_Customer.Company_Name = company_Name;
            tbl_Customer.Contact = contact;
            tbl_Customer.Street_Address = street_Address;
            tbl_Customer.Postal_Code = postal_Code;
            tbl_Customer.City = city;
            tbl_Customer.Country = country;
            return tbl_Customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Customer_ID
        {
            get
            {
                return _Customer_ID;
            }
            set
            {
                if (_Customer_ID != value)
                {
                    OnCustomer_IDChanging(value);
                    ReportPropertyChanging("Customer_ID");
                    _Customer_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Customer_ID");
                    OnCustomer_IDChanged();
                }
            }
        }
        private global::System.Int32 _Customer_ID;
        partial void OnCustomer_IDChanging(global::System.Int32 value);
        partial void OnCustomer_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company_Name
        {
            get
            {
                return _Company_Name;
            }
            set
            {
                OnCompany_NameChanging(value);
                ReportPropertyChanging("Company_Name");
                _Company_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company_Name");
                OnCompany_NameChanged();
            }
        }
        private global::System.String _Company_Name;
        partial void OnCompany_NameChanging(global::System.String value);
        partial void OnCompany_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Organistation_Number
        {
            get
            {
                return _Organistation_Number;
            }
            set
            {
                OnOrganistation_NumberChanging(value);
                ReportPropertyChanging("Organistation_Number");
                _Organistation_Number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Organistation_Number");
                OnOrganistation_NumberChanged();
            }
        }
        private global::System.String _Organistation_Number;
        partial void OnOrganistation_NumberChanging(global::System.String value);
        partial void OnOrganistation_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private global::System.String _Contact;
        partial void OnContactChanging(global::System.String value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_O
        {
            get
            {
                return _C_O;
            }
            set
            {
                OnC_OChanging(value);
                ReportPropertyChanging("C_O");
                _C_O = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_O");
                OnC_OChanged();
            }
        }
        private global::System.String _C_O;
        partial void OnC_OChanging(global::System.String value);
        partial void OnC_OChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Street_Address
        {
            get
            {
                return _Street_Address;
            }
            set
            {
                OnStreet_AddressChanging(value);
                ReportPropertyChanging("Street_Address");
                _Street_Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street_Address");
                OnStreet_AddressChanged();
            }
        }
        private global::System.String _Street_Address;
        partial void OnStreet_AddressChanging(global::System.String value);
        partial void OnStreet_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Postal_Code
        {
            get
            {
                return _Postal_Code;
            }
            set
            {
                OnPostal_CodeChanging(value);
                ReportPropertyChanging("Postal_Code");
                _Postal_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Postal_Code");
                OnPostal_CodeChanged();
            }
        }
        private global::System.String _Postal_Code;
        partial void OnPostal_CodeChanging(global::System.String value);
        partial void OnPostal_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_OnlineShopModel", Name="tbl_Gender")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Gender : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Gender object.
        /// </summary>
        /// <param name="genderID">Initial value of the GenderID property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        public static tbl_Gender Createtbl_Gender(global::System.Int32 genderID, global::System.String gender)
        {
            tbl_Gender tbl_Gender = new tbl_Gender();
            tbl_Gender.GenderID = genderID;
            tbl_Gender.Gender = gender;
            return tbl_Gender;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenderID
        {
            get
            {
                return _GenderID;
            }
            set
            {
                if (_GenderID != value)
                {
                    OnGenderIDChanging(value);
                    ReportPropertyChanging("GenderID");
                    _GenderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GenderID");
                    OnGenderIDChanged();
                }
            }
        }
        private global::System.Int32 _GenderID;
        partial void OnGenderIDChanging(global::System.Int32 value);
        partial void OnGenderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddSeller_tbl_Gender", "tbl_Seller")]
        public EntityCollection<tbl_Seller> tbl_Seller
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Seller>("db_OnlineShopModel.FK_tbl_AddSeller_tbl_Gender", "tbl_Seller");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Seller>("db_OnlineShopModel.FK_tbl_AddSeller_tbl_Gender", "tbl_Seller", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_OnlineShopModel", Name="tbl_Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Product object.
        /// </summary>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        /// <param name="product_Type_ID">Initial value of the Product_Type_ID property.</param>
        /// <param name="brand_ID">Initial value of the Brand_ID property.</param>
        /// <param name="product_Name">Initial value of the Product_Name property.</param>
        /// <param name="product_Info">Initial value of the Product_Info property.</param>
        /// <param name="product_Cost">Initial value of the Product_Cost property.</param>
        /// <param name="seller_ID">Initial value of the Seller_ID property.</param>
        /// <param name="product_Image">Initial value of the Product_Image property.</param>
        public static tbl_Product Createtbl_Product(global::System.Int32 product_ID, global::System.Int32 product_Type_ID, global::System.Int32 brand_ID, global::System.String product_Name, global::System.String product_Info, global::System.Int32 product_Cost, global::System.Int32 seller_ID, global::System.String product_Image)
        {
            tbl_Product tbl_Product = new tbl_Product();
            tbl_Product.Product_ID = product_ID;
            tbl_Product.Product_Type_ID = product_Type_ID;
            tbl_Product.Brand_ID = brand_ID;
            tbl_Product.Product_Name = product_Name;
            tbl_Product.Product_Info = product_Info;
            tbl_Product.Product_Cost = product_Cost;
            tbl_Product.Seller_ID = seller_ID;
            tbl_Product.Product_Image = product_Image;
            return tbl_Product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                if (_Product_ID != value)
                {
                    OnProduct_IDChanging(value);
                    ReportPropertyChanging("Product_ID");
                    _Product_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_ID");
                    OnProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_ID;
        partial void OnProduct_IDChanging(global::System.Int32 value);
        partial void OnProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Type_ID
        {
            get
            {
                return _Product_Type_ID;
            }
            set
            {
                OnProduct_Type_IDChanging(value);
                ReportPropertyChanging("Product_Type_ID");
                _Product_Type_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_Type_ID");
                OnProduct_Type_IDChanged();
            }
        }
        private global::System.Int32 _Product_Type_ID;
        partial void OnProduct_Type_IDChanging(global::System.Int32 value);
        partial void OnProduct_Type_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Brand_ID
        {
            get
            {
                return _Brand_ID;
            }
            set
            {
                OnBrand_IDChanging(value);
                ReportPropertyChanging("Brand_ID");
                _Brand_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Brand_ID");
                OnBrand_IDChanged();
            }
        }
        private global::System.Int32 _Brand_ID;
        partial void OnBrand_IDChanging(global::System.Int32 value);
        partial void OnBrand_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Info
        {
            get
            {
                return _Product_Info;
            }
            set
            {
                OnProduct_InfoChanging(value);
                ReportPropertyChanging("Product_Info");
                _Product_Info = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Info");
                OnProduct_InfoChanged();
            }
        }
        private global::System.String _Product_Info;
        partial void OnProduct_InfoChanging(global::System.String value);
        partial void OnProduct_InfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Cost
        {
            get
            {
                return _Product_Cost;
            }
            set
            {
                OnProduct_CostChanging(value);
                ReportPropertyChanging("Product_Cost");
                _Product_Cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Product_Cost");
                OnProduct_CostChanged();
            }
        }
        private global::System.Int32 _Product_Cost;
        partial void OnProduct_CostChanging(global::System.Int32 value);
        partial void OnProduct_CostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seller_ID
        {
            get
            {
                return _Seller_ID;
            }
            set
            {
                OnSeller_IDChanging(value);
                ReportPropertyChanging("Seller_ID");
                _Seller_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seller_ID");
                OnSeller_IDChanged();
            }
        }
        private global::System.Int32 _Seller_ID;
        partial void OnSeller_IDChanging(global::System.Int32 value);
        partial void OnSeller_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Image
        {
            get
            {
                return _Product_Image;
            }
            set
            {
                OnProduct_ImageChanging(value);
                ReportPropertyChanging("Product_Image");
                _Product_Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Image");
                OnProduct_ImageChanged();
            }
        }
        private global::System.String _Product_Image;
        partial void OnProduct_ImageChanging(global::System.String value);
        partial void OnProduct_ImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Offer_Available
        {
            get
            {
                return _Product_Offer_Available;
            }
            set
            {
                OnProduct_Offer_AvailableChanging(value);
                ReportPropertyChanging("Product_Offer_Available");
                _Product_Offer_Available = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product_Offer_Available");
                OnProduct_Offer_AvailableChanged();
            }
        }
        private global::System.String _Product_Offer_Available;
        partial void OnProduct_Offer_AvailableChanging(global::System.String value);
        partial void OnProduct_Offer_AvailableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Offer_Detail
        {
            get
            {
                return _Product_Offer_Detail;
            }
            set
            {
                OnProduct_Offer_DetailChanging(value);
                ReportPropertyChanging("Product_Offer_Detail");
                _Product_Offer_Detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product_Offer_Detail");
                OnProduct_Offer_DetailChanged();
            }
        }
        private global::System.String _Product_Offer_Detail;
        partial void OnProduct_Offer_DetailChanging(global::System.String value);
        partial void OnProduct_Offer_DetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Replacement_Garentee_available
        {
            get
            {
                return _Product_Replacement_Garentee_available;
            }
            set
            {
                OnProduct_Replacement_Garentee_availableChanging(value);
                ReportPropertyChanging("Product_Replacement_Garentee_available");
                _Product_Replacement_Garentee_available = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Product_Replacement_Garentee_available");
                OnProduct_Replacement_Garentee_availableChanged();
            }
        }
        private global::System.String _Product_Replacement_Garentee_available;
        partial void OnProduct_Replacement_Garentee_availableChanging(global::System.String value);
        partial void OnProduct_Replacement_Garentee_availableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cash_on_Delivery_Available
        {
            get
            {
                return _Cash_on_Delivery_Available;
            }
            set
            {
                OnCash_on_Delivery_AvailableChanging(value);
                ReportPropertyChanging("Cash_on_Delivery_Available");
                _Cash_on_Delivery_Available = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cash_on_Delivery_Available");
                OnCash_on_Delivery_AvailableChanged();
            }
        }
        private global::System.String _Cash_on_Delivery_Available;
        partial void OnCash_on_Delivery_AvailableChanging(global::System.String value);
        partial void OnCash_on_Delivery_AvailableChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_Brand", "tbl_Brand")]
        public tbl_Brand tbl_Brand
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Brand>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Brand", "tbl_Brand").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Brand>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Brand", "tbl_Brand").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Brand> tbl_BrandReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Brand>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Brand", "tbl_Brand");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Brand>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Brand", "tbl_Brand", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_ProductType", "tbl_ProductType")]
        public tbl_ProductType tbl_ProductType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ProductType>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_ProductType", "tbl_ProductType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ProductType>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_ProductType", "tbl_ProductType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_ProductType> tbl_ProductTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ProductType>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_ProductType", "tbl_ProductType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_ProductType>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_ProductType", "tbl_ProductType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_Seller", "tbl_Seller")]
        public tbl_Seller tbl_Seller
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Seller>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Seller", "tbl_Seller").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Seller>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Seller", "tbl_Seller").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Seller> tbl_SellerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Seller>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Seller", "tbl_Seller");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Seller>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Seller", "tbl_Seller", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_OnlineShopModel", Name="tbl_ProductType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ProductType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ProductType object.
        /// </summary>
        /// <param name="product_Type_ID">Initial value of the Product_Type_ID property.</param>
        /// <param name="product_Type">Initial value of the Product_Type property.</param>
        public static tbl_ProductType Createtbl_ProductType(global::System.Int32 product_Type_ID, global::System.String product_Type)
        {
            tbl_ProductType tbl_ProductType = new tbl_ProductType();
            tbl_ProductType.Product_Type_ID = product_Type_ID;
            tbl_ProductType.Product_Type = product_Type;
            return tbl_ProductType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_Type_ID
        {
            get
            {
                return _Product_Type_ID;
            }
            set
            {
                if (_Product_Type_ID != value)
                {
                    OnProduct_Type_IDChanging(value);
                    ReportPropertyChanging("Product_Type_ID");
                    _Product_Type_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_Type_ID");
                    OnProduct_Type_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_Type_ID;
        partial void OnProduct_Type_IDChanging(global::System.Int32 value);
        partial void OnProduct_Type_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Type
        {
            get
            {
                return _Product_Type;
            }
            set
            {
                OnProduct_TypeChanging(value);
                ReportPropertyChanging("Product_Type");
                _Product_Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Type");
                OnProduct_TypeChanged();
            }
        }
        private global::System.String _Product_Type;
        partial void OnProduct_TypeChanging(global::System.String value);
        partial void OnProduct_TypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_ProductType", "tbl_Product")]
        public EntityCollection<tbl_Product> tbl_Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Product>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_ProductType", "tbl_Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Product>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_ProductType", "tbl_Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_OnlineShopModel", Name="tbl_Seller")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Seller : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Seller object.
        /// </summary>
        /// <param name="seller_ID">Initial value of the Seller_ID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="genderID">Initial value of the GenderID property.</param>
        /// <param name="dOB">Initial value of the DOB property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static tbl_Seller Createtbl_Seller(global::System.Int32 seller_ID, global::System.String userID, global::System.String name, global::System.String password, global::System.Int32 genderID, global::System.DateTime dOB, global::System.String email)
        {
            tbl_Seller tbl_Seller = new tbl_Seller();
            tbl_Seller.Seller_ID = seller_ID;
            tbl_Seller.UserID = userID;
            tbl_Seller.Name = name;
            tbl_Seller.Password = password;
            tbl_Seller.GenderID = genderID;
            tbl_Seller.DOB = dOB;
            tbl_Seller.Email = email;
            return tbl_Seller;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seller_ID
        {
            get
            {
                return _Seller_ID;
            }
            set
            {
                if (_Seller_ID != value)
                {
                    OnSeller_IDChanging(value);
                    ReportPropertyChanging("Seller_ID");
                    _Seller_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Seller_ID");
                    OnSeller_IDChanged();
                }
            }
        }
        private global::System.Int32 _Seller_ID;
        partial void OnSeller_IDChanging(global::System.Int32 value);
        partial void OnSeller_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BussinessName
        {
            get
            {
                return _BussinessName;
            }
            set
            {
                OnBussinessNameChanging(value);
                ReportPropertyChanging("BussinessName");
                _BussinessName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BussinessName");
                OnBussinessNameChanged();
            }
        }
        private global::System.String _BussinessName;
        partial void OnBussinessNameChanging(global::System.String value);
        partial void OnBussinessNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenderID
        {
            get
            {
                return _GenderID;
            }
            set
            {
                OnGenderIDChanging(value);
                ReportPropertyChanging("GenderID");
                _GenderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenderID");
                OnGenderIDChanged();
            }
        }
        private global::System.Int32 _GenderID;
        partial void OnGenderIDChanging(global::System.Int32 value);
        partial void OnGenderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private global::System.DateTime _DOB;
        partial void OnDOBChanging(global::System.DateTime value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BussinessTelephone
        {
            get
            {
                return _BussinessTelephone;
            }
            set
            {
                OnBussinessTelephoneChanging(value);
                ReportPropertyChanging("BussinessTelephone");
                _BussinessTelephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BussinessTelephone");
                OnBussinessTelephoneChanged();
            }
        }
        private global::System.String _BussinessTelephone;
        partial void OnBussinessTelephoneChanging(global::System.String value);
        partial void OnBussinessTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeTelephone
        {
            get
            {
                return _HomeTelephone;
            }
            set
            {
                OnHomeTelephoneChanging(value);
                ReportPropertyChanging("HomeTelephone");
                _HomeTelephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeTelephone");
                OnHomeTelephoneChanged();
            }
        }
        private global::System.String _HomeTelephone;
        partial void OnHomeTelephoneChanging(global::System.String value);
        partial void OnHomeTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SkypeName
        {
            get
            {
                return _SkypeName;
            }
            set
            {
                OnSkypeNameChanging(value);
                ReportPropertyChanging("SkypeName");
                _SkypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SkypeName");
                OnSkypeNameChanged();
            }
        }
        private global::System.String _SkypeName;
        partial void OnSkypeNameChanging(global::System.String value);
        partial void OnSkypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdditionalInfo
        {
            get
            {
                return _AdditionalInfo;
            }
            set
            {
                OnAdditionalInfoChanging(value);
                ReportPropertyChanging("AdditionalInfo");
                _AdditionalInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdditionalInfo");
                OnAdditionalInfoChanged();
            }
        }
        private global::System.String _AdditionalInfo;
        partial void OnAdditionalInfoChanging(global::System.String value);
        partial void OnAdditionalInfoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddSeller_tbl_Gender", "tbl_Gender")]
        public tbl_Gender tbl_Gender
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Gender>("db_OnlineShopModel.FK_tbl_AddSeller_tbl_Gender", "tbl_Gender").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Gender>("db_OnlineShopModel.FK_tbl_AddSeller_tbl_Gender", "tbl_Gender").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Gender> tbl_GenderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Gender>("db_OnlineShopModel.FK_tbl_AddSeller_tbl_Gender", "tbl_Gender");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Gender>("db_OnlineShopModel.FK_tbl_AddSeller_tbl_Gender", "tbl_Gender", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_OnlineShopModel", "FK_tbl_AddProduct_tbl_Seller", "tbl_Product")]
        public EntityCollection<tbl_Product> tbl_Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Product>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Seller", "tbl_Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Product>("db_OnlineShopModel.FK_tbl_AddProduct_tbl_Seller", "tbl_Product", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
